"""Smoke test for monocle3._biobabel.

Generated by `biobabel new contract`. Edit to actually exercise the package's
public API (this template only verifies importability).
"""

from __future__ import annotations


def main() -> None:
    import monocle3  # noqa: F401
    print("imported monocle3 successfully")


if __name__ == "__main__":
    main()
