"""Remote data asset registry (auto-generated by data_registry.py).

Do not edit manually.  Re-run ``scripts/data_registry.py generate``
to update after uploading new data.

After publishing to **production** Zenodo, replace sandbox URLs with
production URLs and update the record ID.
"""

CACHE_DIR_NAME = "monocle3-python"

REGISTRY: dict[str, dict[str, str]] = {
    "cao_l2.h5ad": {
        "url": "https://sandbox.zenodo.org/records/492385/files/cao_l2.h5ad?download=1",
        "sha256": "d5b54361516f665c04935232ef9e63b8f685ebfc03c90f6e7306e0c8b1df6ed5",
    },
    "packer_embryo.h5ad": {
        "url": "https://sandbox.zenodo.org/records/492385/files/packer_embryo.h5ad?download=1",
        "sha256": "f7e2286108f5af2ff6ccfc5cec826af182cac5391928bd758e102daf6ad257ed",
    },
}
